#!/bin/bash
path = $(docker inspect -f {{.HostConfig.Binds}} xiaoya | tr -d "[" | tr -d "]")
echo “docker run -d --restart=always --name="xiaoya" -p 5678:80 -p 2345:2345 -p 2346:2346 -v $path xiaoyaliu/alist:latest”
